Feat parse env
not-yet-minishell/minishell pull request #17
Opened 2024-03-26 17:53 UTC by duckgii

# Describe your changes
- 빌트인 함수 파일, 환경변수 파싱 파일, 파이프 뜨는 파일들을 용도별로 딕셔너리에 나눠서 정리했습니다.
- 환경변수를 2차원 배열로 받아 키,값을 '='을 구분자로 해서 연결리스트에 담고 헤드를 반환하는 파서를 만들었습니다.
- 피곤해서 테스트는 안 했습니다.
- 오류나 더 이쁜 폴더명 있으면 피드백 부탁드립니다.

2024-03-27 05:59 UTC, lyssoi requested changes
코멘트 남겼으니 한번 고려해주세요~ 꼭 해당 코멘트 대로 하라는 뜻은 아닙니다. 
이대로 머지하실거면 댓글 남겨주시면 approve하겠습니다
exit 함수도 완성이 된건가요?

2024-03-27 05:59 UTC, lyssoi commented on execute/utile.c
> +}
ft_malloc이 필요한 이유는 할당에 실패했을 때 exit(1)을 하기 위해서인건가요? 👀

2024-03-27 06:03 UTC, lyssoi commented on execute/utile.c
> +}
이 친구는 libft로 가면 좋을것같아요

2024-03-28 01:38 UTC, duckgii commented on parse/parse_env.c
> +	key[idx] = '\0';
네 맞습니다. 새벽에 귀찮아서 그냥 짰는데 수정해보겠습니다

2024-03-28 01:38 UTC, duckgii commented on parse/parse_env.c
> +	value[idx] = '\0';
넵

2024-03-28 01:40 UTC, duckgii commented on parse/parse_env.c
> +		node->next = NULL;
오 좋네요 아니면 메모리풀을 이용하는 방법은 어떨까요? 환경변수를 아예 100개 까지만 만들 수 있도록 제한하는 거죠

2024-03-28 01:40 UTC, duckgii commented on execute/utile.c
> +}
네 exit 때문에 만들었습니다. libft로 옮겨둘게요

2024-03-28 01:41 UTC, duckgii commented
exit은 exit코드 변경 부분을 어떻게할지 고민중이라 그 부분 빼고는 완성했습니다.

2024-03-28 01:49 UTC, lyssoi commented on parse/parse_env.c
> +		node->next = NULL;
오 메모리풀을 이용하는 방법 좋습니다 malloc과 free 과정을 줄일 수 있으니 시간이 빨라지겠네요~

2024-03-28 06:17 UTC, lyssoi approved these changes
통과 드리겠습니다 고생하셨습니다!

2024-03-28 06:18 UTC, merged